### ISSUE TITLE
after installing build pack, node projects stopped working

### ISSUE THREAD

**Issue by webcat12345** [evantahler/heroku-buildpack-notify-slack-deploy#10]
After installing this build pack, `npm command not found` error is happening. Removing this pack resolved this error.

Could you please share your thought on it?

**Comment by evantahler** [comment]
This buildpack should be the last buildpack (after heroku/nodejs) in use in your application.  Can you check the order of your buildpacks?

<img width="1248" alt="Screen Shot 2021-05-26 at 9 26 04 AM" src="https://user-images.githubusercontent.com/303226/119696804-6646e180-be04-11eb-992d-4ddf5ff26023.png">

**Comment by webcat12345** [comment]
Thank you very much for your quick response. As I am going to use very free version, there was no need to add build pack on settings page for this specific app. But I will have a look into right now.

**Comment by evantahler** [comment]
👍 

I've added this to the readme as well - https://github.com/evantahler/heroku-buildpack-notify-slack-deploy/commit/878cebd1b4fb894da7e1cdb939fccaaba3aa3aef

**Comment by webcat12345** [comment]
That's really point of me. Looks like that command you shared in your readme is maybe remove all existing buildpacks and just set only one. I am thinking that's main reason caused issue, anyway, let me test it with reordered buildpack list.

**Comment by webcat12345** [comment]
Cool, it worked! Thank you very much! 

Two things in my mind (of course you knows as well)

* Add caution message that command will remove all existing buildpacks by default, otherwise it will take much time to find out what's causing server issue.
* Way to edit the message.

Thank you very much!

**Comment by evantahler** [comment]
Good advice! I've updated the readme to instruct folks to use the Heroku dashboard for now so we don't replace any buildpacks they might already have.

**Comment by webcat12345** [comment]
It's really nice to meet you! I am also trying to publish some open source libraries, but you are awesome. Followed your profile. :)

**Comment by webcat12345** [comment]
Just let you know, I found some typo from your `actionhero` github repository.
![image](https://user-images.githubusercontent.com/19761422/119700000-bb90ec00-be20-11eb-8dd2-c507a7ecf294.png)

`typescript` is not `tyepscript` never. lol :D

https://github.com/Actionhero/Actionhero

**Comment by evantahler** [comment]
Oh... thank you!
