### ISSUE TITLE
Slack message show prior deploy, not current one

### ISSUE THREAD

**Issue by eterry1388** [evantahler/heroku-buildpack-notify-slack-deploy#3]
It became more obvious after #2 now that we are showing the commit details, but it appears that the slack message being posted is the prior release details, not the current one. Does the ENV variables not update until after the buildpack runs?  We do have this buildpack as the last buildpack.

**Comment by evantahler** [comment]
I was just investigating the same thing! 

It looks like the ENV variables from `runtime-dyno-metadata` (specfically `HEROKU_SLUG_COMMIT`) get updated at the 'release' step, which happens after the 'build' step... which is when this build-pack is invoked.  `HEROKU_SLUG_COMMIT` will be accurate when the app is running, but not when it is building.

so, we probably shouldn't rely on `HEROKU_SLUG_COMMIT`.  We can probably get the latest sha from git directly (`git rev-parse HEAD`).  

Want to give it a try?

**Comment by eterry1388** [comment]
I found this: https://devcenter.heroku.com/changelog-items/630.  Gave it a shot replacing `HEROKU_SLUG_COMMIT` with `SOURCE_VERSION` and it totally worked.

**Comment by evantahler** [comment]
Awesome! Want to send a Pull Request?

**Comment by evantahler** [comment]
I've got it via https://github.com/evantahler/heroku-buildpack-notify-slack-deploy/pull/4
